spring.application.name=mondelys-backend
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]

spring.datasource.url=${DB_URL:jdbc:h2:file:./mondelys_db;MODE=MySQL;AUTO_SERVER=TRUE;DATABASE_TO_LOWER=TRUE}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.web.resources.static-locations=classpath:/static/,file:../

app.jwt.secret=${JWT_SECRET:mondelys_local_dev_jwt_secret_key_2026_change_me}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS:true}

app.mail.from=${MAIL_FROM:no-reply@mondelys.tn}

server.port=8080
server.port=8081